name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-alpha.1.20066.6
        source-url: https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
    - name: Build with dotnet
      run: dotnet build --configuration Release
